# TCL File Generated by Component Editor 16.1
# Mon Feb 19 16:00:48 BRT 2018
# DO NOT MODIFY


# 
# lcd "lcd" v1.0
#  2018.02.19.16:00:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lcd
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCD.v VERILOG PATH LCD.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point LCD_instruction
# 
add_interface LCD_instruction nios_custom_instruction end
set_interface_property LCD_instruction clockCycle 0
set_interface_property LCD_instruction operands 2
set_interface_property LCD_instruction ENABLED true
set_interface_property LCD_instruction EXPORT_OF ""
set_interface_property LCD_instruction PORT_NAME_MAP ""
set_interface_property LCD_instruction CMSIS_SVD_VARIABLES ""
set_interface_property LCD_instruction SVD_ADDRESS_GROUP ""

add_interface_port LCD_instruction DataA dataa Input 32
add_interface_port LCD_instruction DataB datab Input 32
add_interface_port LCD_instruction Result result Output 32
add_interface_port LCD_instruction ClockEnable clk_en Input 1
add_interface_port LCD_instruction Start start Input 1
add_interface_port LCD_instruction Done done Output 1
add_interface_port LCD_instruction Clock clk Input 1
add_interface_port LCD_instruction Reset reset Input 1


# 
# connection point LCD_Conduit
# 
add_interface LCD_Conduit conduit end
set_interface_property LCD_Conduit associatedClock ""
set_interface_property LCD_Conduit associatedReset ""
set_interface_property LCD_Conduit ENABLED true
set_interface_property LCD_Conduit EXPORT_OF ""
set_interface_property LCD_Conduit PORT_NAME_MAP ""
set_interface_property LCD_Conduit CMSIS_SVD_VARIABLES ""
set_interface_property LCD_Conduit SVD_ADDRESS_GROUP ""

add_interface_port LCD_Conduit DataBus databus Output 8
add_interface_port LCD_Conduit OperationEnable operationenable Output 1
add_interface_port LCD_Conduit RegisterSelect registerselect Output 1
add_interface_port LCD_Conduit ReadWrite readwrite Output 1

