# TCL File Generated by Component Editor 16.1
# Wed Jan 31 00:35:50 BRT 2018
# DO NOT MODIFY


# 
# mul "mul" v1.0
#  2018.01.31.00:35:50
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mul
# 
set_module_property DESCRIPTION ""
set_module_property NAME mul
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mul
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CI_multiplicacao
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CI_multiplicacao.v VERILOG PATH CI_multiplicacao.v TOP_LEVEL_FILE
add_fileset_file multiplicacao.v VERILOG PATH multiplicacao.v


# 
# parameters
# 
add_parameter latency INTEGER 0
set_parameter_property latency DEFAULT_VALUE 0
set_parameter_property latency DISPLAY_NAME latency
set_parameter_property latency TYPE INTEGER
set_parameter_property latency UNITS None
set_parameter_property latency HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave rst_n reset Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 16
add_interface_port nios_custom_instruction_slave datab datab Input 16
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave done done Output 1

